#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "note-mark"
name = "note-mark"
description.en = "Markdown notes app"
description.fr = "Application de notes Markdown"

version = "0.14.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://notemark.docs.enchantedcode.co.uk/"
demo = "https://demo.example.com"
admindoc = "https://notemark.docs.enchantedcode.co.uk/docs/"
code = "https://github.com/enchant97/note-mark"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/enchant97/note-mark/archive/refs/tags/v0.14.1.tar.gz"
    sha256 = "27239de766ca7cb4a91273fb4a9f5e877360b9b12857aaa21160bb97f4ef065a"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
